security:
  enableLogin: false

mail:
  enabled: false

system:
  defaultLocale: en-US
  googlevisibility: false # Handled by NGINX reverse proxy
  enableAlphaFunctionality: false
  showUpdate: false
  customHTMLFiles: true
  enableAnalytics: false
  enableUrlToPDF: false
  disableSanitize: false
  fileUploadLimit: '100MB'

ui:
  appName: 'Metropolis PDF'
  homeDescription: 'Running Polarix Container''s ultra-lite FOSS build of Stirling-PDF'
  appNameNavbar: 'Metropolis PDF'

metrics:
  enabled: false
