APP_NAME = Metropolis Forgejo
RUN_USER = git
RUN_MODE = prod
APP_SLOGAN = 
WORK_PATH = /var/lib/gitea

[repository]
ROOT = /var/lib/gitea/git/repositories
DEFAULT_PRIVATE = private
DEFAULT_PUSH_CREATE_PRIVATE = true
MAX_CREATION_LIMIT = -1
PREFERRED_LICENSES = Apache-2.0, MIT
DISABLE_HTTP_GIT = false
USE_COMPAT_SSH_URI = true
GO_GET_CLONE_URL_PROTOCOL = https
DEFAULT_CLOSE_ISSUES_VIA_COMMITS_IN_ANY_BRANCH = false
ENABLE_PUSH_CREATE_USER = false
ENABLE_PUSH_CREATE_ORG = false
DEFAULT_REPO_UNITS = repo.code, repo.issues, repo.pulls
DEFAULT_FORK_REPO_UNITS = repo.code,repo.pulls
DEFAULT_MIRROR_REPO_UNITS = repo.code
DISABLE_MIGRATIONS = false
DISABLE_STARS = false
DISABLE_FORKS = false
DEFAULT_BRANCH = master
ALLOW_ADOPTION_OF_UNADOPTED_REPOSITORIES = false
ALLOW_DELETION_OF_UNADOPTED_REPOSITORIES = false
DISABLE_DOWNLOAD_SOURCE_ARCHIVES = false
ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT = false

[repository.pull-request]
DEFAULT_MERGE_STYLE = squash
DEFAULT_MERGE_MESSAGE_ALL_AUTHORS = true
DEFAULT_MERGE_MESSAGE_MAX_APPROVERS = -1
DEFAULT_MERGE_MESSAGE_OFFICIAL_APPROVERS_ONLY = true
DEFAULT_UPDATE_STYLE = rebase
POPULATE_SQUASH_COMMENT_WITH_COMMIT_MESSAGES = false
ADD_CO_COMMITTER_TRAILERS = true
RETARGET_CHILDREN_ON_MERGE = true

[repository.upload]
ENABLED = true
TEMP_PATH = /tmp/gitea/uploads
FILE_MAX_SIZE = 50
MAX_FILES = 10

[repository.signing]
FORMAT = openpgp
INITIAL_COMMIT = always
DEFAULT_TRUST_MODEL = committer

[repository.local]
LOCAL_COPY_PATH = /tmp/gitea/local-repo

[badges]
ENABLED = true

[cors]
# Handled by nginx
ENABLED = false

[ui]
DEFAULT_THEME = forgejo-auto
SHOW_USER_EMAIL = true
DEFAULT_SHOW_FULL_NAME = false
SEARCH_REPO_DESCRIPTION = true
ONLY_SHOW_RELEVANT_REPOS = false

[markdown]
ENABLE_MATH = true

[server]
APP_DATA_PATH = /var/lib/gitea

USE_PROXY_PROTOCOL = false
PROXY_PROTOCOL_TLS_BRIDGING = false
PROXY_PROTOCOL_ACCEPT_UNKNOWN = false

DOMAIN = forgejo.metropolis.nexus
ROOT_URL = https://forgejo.metropolis.nexus/

HTTP_ADDR = 0.0.0.0
HTTP_PORT = 3000

SSH_DOMAIN = forgejo.metropolis.nexus
DISABLE_SSH = false
START_SSH_SERVER = true
BUILTIN_SSH_SERVER_USER = git
SSH_PORT = 2222
SSH_LISTEN_HOST = 0.0.0.0
SSH_LISTEN_PORT = 2222
SSH_SERVER_CIPHERS = aes256-gcm@openssh.com
SSH_EXPOSE_ANONYMOUS = false

OFFLINE_MODE = true
ENABLE_GZIP = false
LANDING_PAGE = login
ENABLE_ACME = false

LFS_START_SERVER = true
LFS_JWT_SECRET = REDACTED

SSL_MIN_VERSION = TLSv1.3

[database]
DB_TYPE = postgres
HOST = forgejo-postgres:5432
NAME = forgejo
USER = forgejo
PASSWD = REDACTED

SCHEMA = 
SSL_MODE = disable
LOG_SQL = false

[admin]
DEFAULT_EMAIL_NOTIFICATIONS = disabled
DISABLE_REGULAR_ORG_CREATION = false

[security]
INSTALL_LOCK = true
SECRET_KEY =
LOGIN_REMEMBER_DAYS = 30
GLOBAL_TWO_FACTOR_REQUIREMENT = all
REVERSE_PROXY_LIMIT = 1
REVERSE_PROXY_TRUSTED_PROXIES = 192.168.0.102/32
DISABLE_GIT_HOOKS = true
DISABLE_WEBHOOKS = false
ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET = true
IMPORT_LOCAL_PATHS = false
INTERNAL_TOKEN = REDACTED

PASSWORD_HASH_ALGO = argon2
CSRF_COOKIE_HTTP_ONLY = true
MIN_PASSWORD_LENGTH = 12

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[oauth2_client]
REGISTER_EMAIL_CONFIRM = false
OPENID_CONNECT_SCOPES = profile email
ENABLE_AUTO_REGISTRATION = true
USERNAME = nickname
UPDATE_AVATAR = false
ACCOUNT_LINKING = auto

[service]
# These 2 do not matter because of ALLOW_ONLY_EXTERNAL_REGISTRATION
REGISTER_EMAIL_CONFIRM = true
REGISTER_MANUAL_CONFIRM = false

DISABLE_REGISTRATION = false
REQUIRE_EXTERNAL_REGISTRATION_PASSWORD = false
REQUIRE_SIGNIN_VIEW = false
ENABLE_NOTIFY_MAIL = true
ENABLE_BASIC_AUTHENTICATION = false
ENABLE_INTERNAL_SIGNIN = true

ENABLE_REVERSE_PROXY_AUTHENTICATION = false
ENABLE_REVERSE_PROXY_AUTHENTICATION_API = false
ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = false
ENABLE_REVERSE_PROXY_EMAIL = false
ENABLE_REVERSE_PROXY_FULL_NAME = false

ENABLE_CAPTCHA = false
REQUIRE_CAPTCHA_FOR_LOGIN = false
REQUIRE_EXTERNAL_REGISTRATION_CAPTCHA = false

DEFAULT_KEEP_EMAIL_PRIVATE = true
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_USER_IS_RESTRICTED = false
DEFAULT_ENABLE_DEPENDENCIES = true
ALLOW_CROSS_REPOSITORY_DEPENDENCIES = true
ENABLE_USER_HEATMAP = true
ENABLE_TIMETRACKING = true
DEFAULT_ENABLE_TIMETRACKING = false
DEFAULT_ALLOW_ONLY_CONTRIBUTORS_TO_TRACK_TIME = true
EMAIL_DOMAIN_BLOCK_DISPOSABLE = true
SHOW_MILESTONES_DASHBOARD_PAGE = true
AUTO_WATCH_NEW_REPOS = true
AUTO_WATCH_ON_CHANGES = false

DEFAULT_USER_VISIBILITY = public
DEFAULT_ORG_VISIBILITY = public
DEFAULT_ORG_MEMBER_VISIBLE = true

ALLOW_ONLY_INTERNAL_REGISTRATION = false
ALLOW_ONLY_EXTERNAL_REGISTRATION = true
NO_REPLY_ADDRESS = auth.metropolis.nexus
VALID_SITE_URL_SCHEMES = https

[ssh.minimum_key_sizes]
ED25519 = 256
ECDSA = -1
RSA = -1
DSA = -1

[webhook]
SKIP_TLS_VERIFY = false

[mailer]
ENABLED = true
SMTP_ADDR = mail.metropolis.nexus
SMTP_PORT = 465
FROM = forgejo.system@metropolis.nexus
FORCE_TRUST_SERVER_CERT = false
USER = forgejo.system@metropolis.nexus
PASSWD = REDACTED

[email.incoming]
ENABLED = true
REPLY_TO_ADDRESS = forgejo.system+%{token}@metropolis.nexus
HOST = mail.metropolis.nexus
PORT = 993
USERNAME = forgejo.system@metropolis.nexus
PASSWORD = REDACTED

USE_TLS = true
SKIP_TLS_VERIFY = false
DELETE_HANDLED_MESSAGE = true

[cache]
ADAPTER = redis
HOST = redis://forgejo-valkey:6379/0?pool_size=100&idle_timeout=180s

[session]
PROVIDER = redis
PROVIDER_CONFIG = redis://forgejo-valkey:6379/1?pool_size=100&idle_timeout=180s
COOKIE_SECURE = true
DOMAIN = forgejo.metropolis.nexus

[picture]
DISABLE_GRAVATAR = true
ENABLE_FEDERATED_AVATAR = false
AVATAR_STORAGE_TYPE = local
AVATAR_UPLOAD_PATH = /var/lib/gitea/data/avatars
REPOSITORY_AVATAR_STORAGE_TYPE = local
REPOSITORY_AVATAR_UPLOAD_PATH = /var/lib/gitea/data/repo-avatars

[cron.update_checker]
ENABLED = true

[metrics]
ENABLED = false

[oauth2]
ENABLED = false
JWT_SECRET = REDACTED

[federation]
# Waiting for stable
ENABLED = false

[packages]
ENABLED = true

[mirror]
ENABLED = true
DISABLE_NEW_PULL = false
DISABLE_NEW_PUSH = false

[attachment]
ENABLED = true
PATH = /var/lib/gitea/data/attachments

[lfs]
PATH = /var/lib/gitea/git/lf

[log]
ROOT_PATH = /var/lib/gitea/data/log
MODE = console
LEVEL = info

[quota]
ENABLED = true

[quota.default]
TOTAL = 10G

[proxy]
PROXY_ENABLED = false

[actions]
# Will be enabled once runners are ready
ENABLED = false

[moderation]
ENABLED = true
KEEP_RESOLVED_REPORTS_FOR = 30d

[other]
SHOW_FOOTER_VERSION = false
SHOW_FOOTER_TEMPLATE_LOAD_TIME = true
SHOW_FOOTER_POWERED_BY = true
ENABLE_SITEMAP = true
ENABLE_FEED = true